import {
    GraphQLObjectType,
    GraphQLString,
    GraphQLSchema,
    GraphQLList,
    GraphQLNonNull,
    GraphQLFloat,
    GraphQLInt
  } from 'graphql';
  
  const price = new GraphQLObjectType({
    name: 'price',
    fields: {
        open: { type: new GraphQLNonNull(GraphQLFloat) },
        High: { type: new GraphQLNonNull(GraphQLFloat) },
        Low: { type: new GraphQLNonNull(GraphQLFloat) },
        Close: { type: new GraphQLNonNull(GraphQLFloat) },
        Volume: { type: new GraphQLNonNull(GraphQLInt) },
        Dividends: { type: new GraphQLNonNull(GraphQLFloat) },
        Stock_Splits: { type: new GraphQLNonNull(GraphQLFloat) },    
    },
    });
    
    const IncomeStmtType = new GraphQLObjectType({
        name: 'IncomeStmt',
        fields: () => ({
          Tax_Effect_Of_Unusual_Items: { type: GraphQLFloat, defaultValue: null },
          Tax_Rate_For_Calcs: { type: GraphQLFloat, defaultValue: null },
          Normalized_EBITDA: { type: GraphQLFloat, defaultValue: null },
          Total_Unusual_Items: { type: GraphQLFloat, defaultValue: null },
          Total_Unusual_Items_Excluding_Goodwill: { type: GraphQLFloat, defaultValue: null },
          Net_Income_From_Continuing_Operation_Net_Minority_Interest: { type: GraphQLFloat, defaultValue: null },
          Reconciled_Depreciation: { type: GraphQLFloat, defaultValue: null },
          Reconciled_Cost_Of_Revenue: { type: GraphQLFloat, defaultValue: null },
          EBITDA: { type: GraphQLFloat, defaultValue: null },
          EBIT: { type: GraphQLFloat, defaultValue: null },
          Net_Interest_Income: { type: GraphQLFloat, defaultValue: null },
          Interest_Expense: { type: GraphQLFloat, defaultValue: null },
          Normalized_Income: { type: GraphQLFloat, defaultValue: null },
          Net_Income_From_Continuing_And_Discontinued_Operation: { type: GraphQLFloat, defaultValue: null },
          Total_Expenses: { type: GraphQLFloat, defaultValue: null },
          Diluted_Average_Shares: { type: GraphQLFloat, defaultValue: null },
          Basic_Average_Shares: { type: GraphQLFloat, defaultValue: null },
          Diluted_EPS: { type: GraphQLFloat, defaultValue: null },
          Basic_EPS: { type: GraphQLFloat, defaultValue: null },
          Diluted_NI_Availto_Com_Stockholders: { type: GraphQLFloat, defaultValue: null },
          Net_Income_Common_Stockholders: { type: GraphQLFloat, defaultValue: null },
          Preferred_Stock_Dividends: { type: GraphQLFloat, defaultValue: null },
          Net_Income: { type: GraphQLFloat, defaultValue: null },
          Minority_Interests: { type: GraphQLFloat, defaultValue: null },
          Net_Income_Including_Noncontrolling_Interests: { type: GraphQLFloat, defaultValue: null },
          Net_Income_Continuous_Operations: { type: GraphQLFloat, defaultValue: null },
          Tax_Provision: { type: GraphQLFloat, defaultValue: null },
          Pretax_Income: { type: GraphQLFloat, defaultValue: null },
          Other_Income_Expense: { type: GraphQLFloat , defaultValue: null},
          Special_Income_Charges: { type: GraphQLFloat, defaultValue: null },
          Gain_On_Sale_Of_PPE: { type: GraphQLFloat, defaultValue: null },
          Write_Off: { type: GraphQLFloat, defaultValue: null },
          Impairment_Of_Capital_Assets: { type: GraphQLFloat, defaultValue: null },
          Earnings_From_Equity_Interest: { type: GraphQLFloat, defaultValue: null },
          Gain_On_Sale_Of_Security: { type: GraphQLFloat, defaultValue: null },
          Net_Non_Operating_Interest_Income_Expense: { type: GraphQLFloat, defaultValue: null },
          Interest_Expense_Non_Operating: { type: GraphQLFloat , defaultValue: null},
          Operating_Income: { type: GraphQLFloat, defaultValue: null },
          Operating_Expense: { type: GraphQLFloat, defaultValue: null },
          Other_Operating_Expenses: { type: GraphQLFloat , defaultValue: null},
          Depreciation_Amortization_Depletion_Income_Statement: { type: GraphQLFloat , defaultValue: null},
          Depreciation_And_Amortization_In_Income_Statement: { type: GraphQLFloat , defaultValue: null},
          Selling_General_And_Administration: { type: GraphQLFloat, defaultValue: null },
          General_And_Administrative_Expense: { type: GraphQLFloat, defaultValue: null },
          Other_GandA: { type: GraphQLFloat, defaultValue: null },
          Salaries_And_Wages: { type: GraphQLFloat, defaultValue: null },
          Gross_Profit: { type: GraphQLFloat, defaultValue: null },
          Cost_Of_Revenue: { type: GraphQLFloat, defaultValue: null },
          Total_Revenue: { type: GraphQLFloat, defaultValue: null },
          Operating_Revenue: { type: GraphQLFloat, defaultValue: null },
        }),
      });
    
    const CashflowType = new GraphQLObjectType({
        name: 'Cashflow',
        fields: () => ({
        
            free_cash_flow: { type: GraphQLFloat, "default": null },
            repurchase_of_capital_stock: { type: GraphQLFloat, "default": null },    
            repayment_of_debt: { type: GraphQLFloat, "default": null },    
            issuance_of_debt: { type: GraphQLFloat, "default": null },    
            issuance_of_capital_stock: { type: GraphQLFloat, "default": null },    
            capital_expenditure: { type: GraphQLFloat, "default": null },    
            end_cash_position: { type: GraphQLFloat, "default": null },    
            beginning_cash_position: { type: GraphQLFloat, "default": null },    
            effect_of_exchange_rate_changes: { type: GraphQLFloat, "default": null },    
            changes_in_cash: { type: GraphQLFloat, "default": null },    
            financing_cash_flow: { type: GraphQLFloat, "default": null },    
            cash_flow_from_continuing_financing_activities: { type: GraphQLFloat, "default": null },    
            net_other_financing_charges: { type: GraphQLFloat, "default": null },    
            interest_paid_cff: { type: GraphQLFloat, "default": null },    
            proceeds_from_stock_option_exercised: { type: GraphQLFloat, "default": null },    
            cash_dividends_paid: { type: GraphQLFloat, "default": null },    
            net_preferred_stock_issuance: { type: GraphQLFloat, "default": null },    
            preferred_stock_payments: { type: GraphQLFloat, "default": null },          
            net_common_stock_issuance: { type: GraphQLFloat, "default": null },          
            common_stock_issuance: { type: GraphQLFloat, "default": null },          
            net_issuance_payments_of_debt: { type: GraphQLFloat, "default": null },
            net_long_term_debt_issuance: { type: GraphQLFloat, "default": null },  
            long_term_debt_payments: { type: GraphQLFloat, "default": null },
            long_term_debt_issuance: { type: GraphQLFloat, "default": null },          
            investing_cash_flow: { type: GraphQLFloat, "default": null },          
            cash_flow_from_continuing_investing_activities: { type: GraphQLFloat, "default": null },          
            net_other_investing_changes: { type: GraphQLFloat, "default": null },          
            net_business_purchase_and_sale: { type: GraphQLFloat, "default": null },         
            purchase_of_business: { type: GraphQLFloat, "default": null },    
            net_ppe_purchase_and_sale: { type: GraphQLFloat, "default": null },    
            purchase_of_ppe: { type: GraphQLFloat, "default": null },    
            operating_cash_flow: { type: GraphQLFloat, "default": null },    
            cash_flow_from_continuing_operating_activities: { type: GraphQLFloat, "default": null },    
            taxes_refund_paid: { type: GraphQLFloat, "default": null },    
            interest_paid_cfo: { type: GraphQLFloat, "default": null },    
            dividend_received_cfo: { type: GraphQLFloat, "default": null },    
            change_in_working_capital: { type: GraphQLFloat, "default": null },   
            other_non_cash_items: { type: GraphQLFloat, "default": null },    
            asset_impairment_charge: { type: GraphQLFloat, "default": null },    
            deferred_tax: { type: GraphQLFloat, "default": null },    
            deferred_income_tax: { type: GraphQLFloat, "default": null },    
            depreciation_amortization_depletion: { type: GraphQLFloat, "default": null },    
            depreciation_and_amortization: { type: GraphQLFloat, "default": null },    
            operating_gains_losses: { type: GraphQLFloat, "default": null },    
            earnings_losses_from_equity_investments: { type: GraphQLFloat, "default": null },    
            gain_loss_on_investment_securities: { type: GraphQLFloat, "default": null },    
            net_foreign_currency_exchange_gain_loss: { type: GraphQLFloat, "default": null },    
            net_income_from_continuing_operations: { type: GraphQLFloat, "default": null },
              
            }),
              
        });
    
    
    const BalanceSheetType = new GraphQLObjectType({
        name: 'BalanceSheet',
        fields: () => ({
            ordinary_shares_number: { type: GraphQLFloat, "default": null },
            share_issued: { type: GraphQLFloat, "default": null },
            net_debt: { type: GraphQLFloat, "default": null },
            total_debt: { type: GraphQLFloat, "default": null },
            tangible_book_value: { type: GraphQLFloat, "default": null },
            invested_capital: { type: GraphQLFloat, "default": null },
            working_capital: { type: GraphQLFloat, "default": null },
            net_tangible_assets: { type: GraphQLFloat, "default": null },
            capital_lease_obligations: { type: GraphQLFloat, "default": null },
            common_stock_equity: { type: GraphQLFloat, "default": null },
            preferred_stock_equity: { type: GraphQLFloat, "default": null },
            total_capitalization: { type: GraphQLFloat, "default": null },
            total_equity_gross_minority_interest: { type: GraphQLFloat, "default": null },
            minority_interest: { type: GraphQLFloat, "default": null },
            stockholders_equity: { type: GraphQLFloat, "default": null },
            gains_losses_not_affecting_retained_earnings: { type: GraphQLFloat, "default": null },
            other_equity_adjustments: { type: GraphQLFloat, "default": null },
            foreign_currency_translation_adjustments: { type: GraphQLFloat, "default": null },
            minimum_pension_liabilities: { type: GraphQLFloat, "default": null },
            retained_earnings: { type: GraphQLFloat, "default": null },
            capital_stock: { type: GraphQLFloat, "default": null },
            common_stock: { type: GraphQLFloat, "default": null },
            preferred_stock: { type: GraphQLFloat, "default": null },
            total_liabilities_net_minority_interest: { type: GraphQLFloat, "default": null },
            total_non_current_liabilities_net_minority_interest: { type: GraphQLFloat, "default": null },
            other_non_current_liabilities: { type: GraphQLFloat, "default": null },
            derivative_product_liabilities: { type: GraphQLFloat, "default": null },
            non_current_deferred_liabilities: { type: GraphQLFloat, "default": null },
            non_current_deferred_revenue: { type: GraphQLFloat, "default": null },
            non_current_deferred_taxes_liabilities: { type: GraphQLFloat, "default": null },
            long_term_debt_and_capital_lease_obligation: { type: GraphQLFloat, "default": null },
            long_term_capital_lease_obligation: { type: GraphQLFloat, "default": null },
            long_term_debt: { type: GraphQLFloat, "default": null },
            long_term_provisions: { type: GraphQLFloat, "default": null },
            current_liabilities: { type: GraphQLFloat, "default": null },
            other_current_liabilities: { type: GraphQLFloat, "default": null },
            current_deferred_liabilities: { type: GraphQLFloat, "default": null },
            current_deferred_revenue: { type: GraphQLFloat, "default": null },
            current_debt_and_capital_lease_obligation: { type: GraphQLFloat, "default": null },
            current_debt: { type: GraphQLFloat, "default": null },
            other_current_borrowings: { type: GraphQLFloat, "default": null },
            current_provisions: { type: GraphQLFloat, "default": null },
            payables_and_accrued_expenses: { type: GraphQLFloat, "default": null },
            current_accrued_expenses: { type: GraphQLFloat, "default": null },
            interest_payable: { type: GraphQLFloat, "default": null },
            payables: { type: GraphQLFloat, "default": null },
            dividends_payable: { type: GraphQLFloat, "default": null },
            total_tax_payable: { type: GraphQLFloat, "default": null },
            accounts_payable: { type: GraphQLFloat, "default": null },
            total_assets: { type: GraphQLFloat, "default": null },
            total_non_current_assets: { type: GraphQLFloat, "default": null },
            other_non_current_assets: { type: GraphQLFloat, "default": null },
            non_current_deferred_assets: { type: GraphQLFloat, "default": null },
            non_current_deferred_taxes_assets: { type: GraphQLFloat, "default": null },
            non_current_accounts_receivable: { type: GraphQLFloat, "default": null },
            financial_assets: { type: GraphQLFloat, "default": null },
            investments_and_advances: { type: GraphQLFloat, "default": null },
            long_term_equity_investment: { type: GraphQLFloat, "default": null },
            goodwill_and_other_intangible_assets: { type: GraphQLFloat, "default": null },
            other_intangible_assets: { type: GraphQLFloat, "default": null },
            goodwill: { type: GraphQLFloat, "default": null },
            net_ppe: { type: GraphQLFloat, "default": null },
            accumulated_depreciation: { type: GraphQLFloat, "default": null },
            gross_ppe: { type: GraphQLFloat, "default": null },
            construction_in_progress: { type: GraphQLFloat, "default": null },
            other_properties: { type: GraphQLFloat, "default": null },
            machinery_furniture_equipment: { type: GraphQLFloat, "default": null },
            buildings_and_improvements: { type: GraphQLFloat, "default": null },
            land_and_improvements: { type: GraphQLFloat, "default": null },
            properties: { type: GraphQLFloat, "default": null },
            current_assets: { type: GraphQLFloat, "default": null },
            hedging_assets_current: { type: GraphQLFloat, "default": null },
            restricted_cash: { type: GraphQLFloat, "default": null },
            prepaid_assets: { type: GraphQLFloat, "default": null },
            inventory: { type: GraphQLFloat, "default": null },
            other_inventories: { type: GraphQLFloat, "default": null },
            raw_materials: { type: GraphQLFloat, "default": null },
            receivables: { type: GraphQLFloat, "default": null },
            other_receivables: { type: GraphQLFloat, "default": null },
            taxes_receivable: { type: GraphQLFloat, "default": null },
            accounts_receivable: { type: GraphQLFloat, "default": null },
            cash_cash_equivalents_and_short_term_investments: { type: GraphQLFloat, "default": null },
            cash_and_cash_equivalents: { type: GraphQLFloat, "default": null },
    
        })})
    
    
    const CompanyOfficerType = new GraphQLObjectType({
    
        name: 'CompanyOfficers',
        
        fields: () => ({
        
            maxAge: { type: GraphQLInt, "default": null },    
            name: { type: GraphQLString, "default": null },    
            age: { type: GraphQLInt, "default": null },    
            title: { type: GraphQLString, "default": null },    
            yearBorn: { type: GraphQLInt, "default": null },    
            fiscalYear: { type: GraphQLInt, "default": null },    
            totalPay: { type: GraphQLFloat, "default": null },    
            exercisedValue: { type: GraphQLFloat, "default": null },    
            unexercisedValue: { type: GraphQLFloat, "default": null }
        
        }),
        
        });
    
    const InfoType = new GraphQLObjectType({
        
        name: 'Info',
        
        fields: () => ({
        
            address1: { type: GraphQLString, defaultValue: null },    
            address2: { type: GraphQLString, defaultValue: null },    
            city: { type: GraphQLString, defaultValue: null },    
            state: { type: GraphQLString, defaultValue: null },    
            zip: { type: GraphQLString, defaultValue: null },    
            country: { type: GraphQLString, defaultValue: null },    
            phone: { type: GraphQLString, defaultValue: null },    
            website: { type: GraphQLString, defaultValue: null },    
            industry: { type: GraphQLString, defaultValue: null },    
            industryDisp: { type: GraphQLString, defaultValue: null },    
            sector: { type: GraphQLString, defaultValue: null },    
            sectorDisp: { type: GraphQLString, defaultValue: null },    
            longBusinessSummary: { type: GraphQLString, defaultValue: null },    
            fullTimeEmployees: { type: GraphQLInt, defaultValue: null },    
            companyOfficers: { type: new GraphQLList(CompanyOfficerType)},
            auditRisk: { type: GraphQLInt, defaultValue: null },
            boardRisk: { type: GraphQLInt, defaultValue: null },
            compensationRisk: { type: GraphQLInt, defaultValue: null },
            shareHolderRightsRisk: { type: GraphQLInt, defaultValue: null },
            overallRisk: { type: GraphQLInt, defaultValue: null }, 
            governanceEpochDate: { type: GraphQLInt, defaultValue: null },
            compensationAsOfEpochDate: { type: GraphQLInt, defaultValue: null },
            maxAge: { type: GraphQLInt, defaultValue: null },
            priceHint: { type: GraphQLInt, defaultValue: null },
            previousClose: { type: GraphQLFloat, defaultValue: null },
            open: { type: GraphQLFloat, defaultValue: null },
            dayLow: { type: GraphQLFloat, defaultValue: null },
            dayHigh: { type: GraphQLFloat, defaultValue: null },
            regularMarketPreviousClose: { type: GraphQLFloat, defaultValue: null },
            regularMarketOpen: { type: GraphQLFloat, defaultValue: null },
            regularMarketDayLow: { type: GraphQLFloat, defaultValue: null },
            regularMarketDayHigh: { type: GraphQLFloat, defaultValue: null },
            dividendRate: { type: GraphQLFloat, defaultValue: null },
            dividendYield: { type: GraphQLFloat, defaultValue: null },
            exDividendDate: { type: GraphQLInt, defaultValue: null },
            payoutRatio: { type: GraphQLFloat, defaultValue: null },
            fiveYearAvgDividendYield: { type: GraphQLFloat, defaultValue: null },
            beta: { type: GraphQLFloat, defaultValue: null },
            trailingPE: { type: GraphQLFloat, defaultValue: null },
            forwardPE: { type: GraphQLFloat, defaultValue: null },
            volume: { type: GraphQLInt, defaultValue: null },
            regularMarketVolume: { type: GraphQLInt, defaultValue: null },
            averageVolume: { type: GraphQLInt, defaultValue: null },
            averageVolume10days: { type: GraphQLInt, defaultValue: null },
            averageDailyVolume10Day: { type: GraphQLFloat, defaultValue: null },
            bid: { type: GraphQLFloat, defaultValue: null },
            ask: { type: GraphQLFloat, defaultValue: null },
            bidSize: { type: GraphQLInt, defaultValue: null },
            askSize: { type: GraphQLInt, defaultValue: null },
            marketCap: { type: GraphQLInt, defaultValue: null },
            fiftyTwoWeekLow: { type: GraphQLFloat, defaultValue: null },
            fiftyTwoWeekHigh: { type: GraphQLFloat, defaultValue: null },
            priceToSalesTrailing12Months: { type: GraphQLFloat, defaultValue: null },
            fiftyDayAverage: { type: GraphQLFloat, defaultValue: null },
            twoHundredDayAverage: { type: GraphQLFloat, defaultValue: null },
            trailingAnnualDividendRate: { type: GraphQLFloat, defaultValue: null },
            trailingAnnualDividendYield: { type: GraphQLFloat, defaultValue: null },
            currency: { type: GraphQLString, defaultValue: null },
            enterpriseValue: { type: GraphQLInt, defaultValue: null },
            profitMargins: { type: GraphQLFloat, defaultValue: null },
            floatShares: { type: GraphQLInt, defaultValue: null },
            sharesOutstanding: { type: GraphQLInt, defaultValue: null },
            sharesShort: { type: GraphQLInt, defaultValue: null },
            sharesShortPriorMonth: { type: GraphQLInt, defaultValue: null },
            sharesShortPreviousMonthDate: { type: GraphQLInt, defaultValue: null },
            dateShortInterest: { type: GraphQLInt, defaultValue: null },
            sharesPercentSharesOut: { type: GraphQLFloat, defaultValue: null },
            heldPercentInsiders: { type: GraphQLFloat, defaultValue: null },
            heldPercentInstitutions: { type: GraphQLFloat, defaultValue: null },
            shortRatio: { type: GraphQLFloat, defaultValue: null },
            impliedSharesOutstanding: { type: GraphQLInt, defaultValue: null },
            bookValue: { type: GraphQLFloat, defaultValue: null },
            priceToBook: { type: GraphQLFloat, defaultValue: null },
            lastFiscalYearEnd: { type: GraphQLInt, defaultValue: null },
            nextFiscalYearEnd: { type: GraphQLInt, defaultValue: null },
            mostRecentQuarter: { type: GraphQLInt, defaultValue: null },
            earningsQuarterlyGrowth: { type: GraphQLFloat, defaultValue: null },
            netIncomeToCommon: { type: GraphQLInt, defaultValue: null },
            trailingEps: { type: GraphQLFloat, defaultValue: null },
            forwardEps: { type: GraphQLFloat, defaultValue: null },
            pegRatio: { type: GraphQLFloat, defaultValue: null },
            enterpriseToRevenue: { type: GraphQLFloat, defaultValue: null },
            enterpriseToEbitda: { type: GraphQLFloat, defaultValue: null },
            annualChange: { type: GraphQLFloat, defaultValue: null },
            SandP52WeekChange: { type: GraphQLFloat, defaultValue: null },
            lastDividendValue: { type: GraphQLFloat, defaultValue: null },
            lastDividendDate: { type: GraphQLFloat, defaultValue: null },
            exchange: { type: GraphQLString, defaultValue: null },
            quoteType: { type: GraphQLString, defaultValue: null },
            symbol: { type: GraphQLString, defaultValue: null },
            underlyingSymbol: { type: GraphQLString, defaultValue: null },
            shortName: { type: GraphQLString, defaultValue: null },
            longName: { type: GraphQLString, defaultValue: null },
            firstTradeDateEpochUtc: { type: GraphQLInt, defaultValue: null },
            timeZoneFullName: { type: GraphQLString, defaultValue: null },
            timeZoneShortName: { type: GraphQLString, defaultValue: null },
            uuid: { type: GraphQLString, defaultValue: null },
            messageBoardId: { type: GraphQLString, defaultValue: null },
            gmtOffSetMilliseconds: { type: GraphQLInt, defaultValue: null },
            currentPrice: { type: GraphQLFloat, defaultValue: null },
            targetHighPrice: { type: GraphQLFloat, defaultValue: null },
            targetLowPrice: { type: GraphQLFloat, defaultValue: null },
            targetMeanPrice: { type: GraphQLFloat, defaultValue: null },
            targetMedianPrice: { type: GraphQLFloat, defaultValue: null },
            recommendationMean: { type: GraphQLFloat, defaultValue: null },
            recommendationKey: { type: GraphQLString, defaultValue: null },
            numberOfAnalystOpinions: { type: GraphQLInt, defaultValue: null },
            totalCash: { type: GraphQLInt, defaultValue: null },
            totalCashPerShare: { type: GraphQLFloat, defaultValue: null },
            ebitda: { type: GraphQLInt, defaultValue: null },
            totalDebt: { type: GraphQLInt, defaultValue: null },
            quickRatio: { type: GraphQLFloat, defaultValue: null },
            currentRatio: { type: GraphQLFloat, defaultValue: null },
            totalRevenue: { type: GraphQLInt, defaultValue: null },
            debtToEquity: { type: GraphQLFloat, defaultValue: null },
            revenuePerShare: { type: GraphQLFloat, defaultValue: null },
            returnOnAssets: { type: GraphQLFloat, defaultValue: null },
            returnOnEquity: { type: GraphQLFloat, defaultValue: null },
            grossProfits: { type: GraphQLInt, defaultValue: null },
            freeCashflow: { type: GraphQLInt, defaultValue: null },
            operatingCashflow: { type: GraphQLInt, defaultValue: null },
            earningsGrowth: { type: GraphQLFloat, defaultValue: null },
            revenueGrowth: { type: GraphQLFloat, defaultValue: null },
            grossMargins: { type: GraphQLFloat, defaultValue: null },
            ebitdaMargins: { type: GraphQLFloat, defaultValue: null },
            operatingMargins: { type: GraphQLFloat, defaultValue: null },
            financialCurrency: { type: GraphQLString, defaultValue: null },
            trailingPegRatio: { type: GraphQLFloat, defaultValue: null },
            isin: { type: GraphQLFloat, defaultValue: null },
        
        }),
        
        });
    
    const institutions = new GraphQLObjectType({
      name: 'institutions',
      fields: () => ({
        Holder: { type: GraphQLString },
        Shares: { type: GraphQLFloat },
        DateReported: { type: GraphQLString },
        Out_percent: { type: GraphQLFloat },
        Value: { type: GraphQLFloat },
      }),
    });


const FinancialDataType = new GraphQLObjectType({

    name: 'FinancialData',

    fields: () => ({
      company : { type: new GraphQLNonNull( GraphQLString)},
      price: { type: price},
      income_stmt: {type: IncomeStmtType},
      income_stmt_date: { type: GraphQLString },
      cashflow: {type: CashflowType},
      cashflow_date: {type: GraphQLString, defaultValue:null},
      balance_sheet: {type: BalanceSheetType},  
      balance_sheet_date: { type: GraphQLString },  
      info: { type: InfoType },  
      job_family: { type: GraphQLString },    
      institutions: {   
        type: institutions,   
        resolve(parent) {  
          return parent.institutions;      
        }    },    
    event_fingerprint: { type: GraphQLString },
    event_timestamp: { type: GraphQLString },
  
  })});

const RootQuery = new GraphQLObjectType({
  
    name: 'RootQueryType',  
    fields: {  
      getFinancialData: {  
        type: FinancialDataType,  
        resolve: () => {
          return {
            finance:{
            "company": {"type": "string"},
            "price": {"type": "object",
                      "properties": {
                        "Open": {"type": "number"},
                        "High": {"type": "number"},
                        "Low": {"type": "number"},
                        "Close": {"type": "number"},
                        "Volume": {"type": "number"},
                        "Dividends": {"type": "number"},
                        "Stock Splits": {"type": "number"},
                      },
                      "required": ["Open", "High", "Low", "Close", "Volume", "Dividends", "Stock Splits"]
                    },
            "income_stmt": {"type": "object",
                            "properties": {
                                "Tax Effect Of Unusual Items": {"type": ["number", "null"], "default": null},
                                "Tax Rate For Calcs": {"type": ["number", "null"], "default": null},
                                "Normalized EBITDA": {"type": ["number", "null"], "default": null},
                                "Total Unusual Items": {"type": ["number", "null"], "default": null},
                                "Total Unusual Items Excluding Goodwill": {"type": ["number", "null"], "default": null},
                                "Net Income From Continuing Operation Net Minority Interest": {"type": ["number", "null"], "default": null},
                                "Reconciled Depreciation": {"type": ["number", "null"], "default": null},
                                "Reconciled Cost Of Revenue": {"type": ["number", "null"], "default": null},
                                "EBITDA": {"type": ["number", "null"], "default": null},
                                "EBIT": {"type": ["number", "null"], "default": null},
                                "Net Interest Income": {"type": ["number", "null"], "default": null},
                                "Interest Expense": {"type": ["number", "null"], "default": null},
                                "Normalized Income": {"type": ["number", "null"], "default": null},
                                "Net Income From Continuing And Discontinued Operation": {"type": ["number", "null"], "default": null},
                                "Total Expenses": {"type": ["number", "null"], "default": null},
                                "Diluted Average Shares": {"type": ["number", "null"], "default": null},
                                "Basic Average Shares": {"type": ["number", "null"], "default": null},
                                "Diluted EPS": {"type": ["number", "null"], "default": null},
                                "Basic EPS": {"type": ["number", "null"], "default": null},
                                "Diluted NI Availto Com Stockholders": {"type": ["number", "null"], "default": null},
                                "Net Income Common Stockholders": {"type": ["number", "null"], "default": null},
                                "Preferred Stock Dividends": {"type": ["number", "null"], "default": null},
                                "Net Income": {"type": ["number", "null"], "default": null},
                                "Minority Interests": {"type": ["number", "null"], "default": null},
                                "Net Income Including Noncontrolling Interests": {"type": ["number", "null"], "default": null},
                                "Net Income Continuous Operations": {"type": ["number", "null"], "default": null},
                                "Tax Provision": {"type": ["number", "null"], "default": null},
                                "Pretax Income": {"type": ["number", "null"], "default": null},
                                "Other Income Expense": {"type": ["number", "null"], "default": null},
                                "Special Income Charges": {"type": ["number", "null"], "default": null},
                                "Gain On Sale Of Ppe": {"type": ["number", "null"], "default": null},
                                "Write Off": {"type": ["number", "null"], "default": null},
                                "Impairment Of Capital Assets": {"type": ["number", "null"], "default": null},
                                "Earnings From Equity Interest": {"type": ["number", "null"], "default": null},
                                "Gain On Sale Of Security": {"type": ["number", "null"], "default": null},
                                "Net Non Operating Interest Income Expense": {"type": ["number", "null"], "default": null},
                                "Interest Expense Non Operating": {"type": ["number", "null"], "default": null},
                                "Operating Income": {"type": ["number", "null"], "default": null},
                                "Operating Expense": {"type": ["number", "null"], "default": null},
                                "Other Operating Expenses": {"type": ["number", "null"], "default": null},
                                "Depreciation Amortization Depletion Income Statement": {"type": ["number", "null"], "default": null},
                                "Depreciation And Amortization In Income Statement": {"type": ["number", "null"], "default": null},
                                "Selling General And Administration": {"type": ["number", "null"], "default": null},
                                "General And Administrative Expense": {"type": ["number", "null"], "default": null},
                                "Other Gand A": {"type": ["number", "null"], "default": null},
                                "Salaries And Wages": {"type": ["number", "null"], "default": null},
                                "Gross Profit": {"type": ["number", "null"], "default": null},
                                "Cost Of Revenue": {"type": ["number", "null"], "default": null},
                                "Total Revenue": {"type": ["number", "null"], "default": null},
                                "Operating Revenue": {"type": ["number", "null"], "default": null},
                            }
                    },
            "income_stmt_date": {"type": ["string", "null"], "default": null},
            "cashflow": {"type": "object",
                         "properties": {
                            "Free Cash Flow": {"type": ["number", "null"], "default": null},
                            "Repurchase Of Capital Stock": {"type": ["number", "null"], "default": null},
                            "Repayment Of Debt": {"type": ["number", "null"], "default": null},
                            "Issuance Of Debt": {"type": ["number", "null"], "default": null},
                            "Issuance Of Capital Stock": {"type": ["number", "null"], "default": null},
                            "Capital Expenditure": {"type": ["number", "null"], "default": null},
                            "End Cash Position": {"type": ["number", "null"], "default": null},
                            "Beginning Cash Position": {"type": ["number", "null"], "default": null},
                            "Effect Of Exchange Rate Changes": {"type": ["number", "null"], "default": null},
                            "Changes In Cash": {"type": ["number", "null"], "default": null},
                            "Financing Cash Flow": {"type": ["number", "null"], "default": null},
                            "Cash Flow From Continuing Financing Activities": {"type": ["number", "null"], "default": null},
                            "Net Other Financing Charges": {"type": ["number", "null"], "default": null},
                            "Interest Paid Cff": {"type": ["number", "null"], "default": null},
                            "Proceeds From Stock Option Exercised": {"type": ["number", "null"], "default": null},
                            "Cash Dividends Paid": {"type": ["number", "null"], "default": null},
                            "Net Preferred Stock Issuance": {"type": ["number", "null"], "default": null},
                            "Preferred Stock Payments": {"type": ["number", "null"], "default": null},
                            "Net Common Stock Issuance": {"type": ["number", "null"], "default": null},
                            "Common Stock Issuance": {"type": ["number", "null"], "default": null},
                            "Net Issuance Payments Of Debt": {"type": ["number", "null"], "default": null},
                            "Net Long Term Debt Issuance": {"type": ["number", "null"], "default": null},
                            "Long Term Debt Payments": {"type": ["number", "null"], "default": null},
                            "Long Term Debt Issuance": {"type": ["number", "null"], "default": null},
                            "Investing Cash Flow": {"type": ["number", "null"], "default": null},
                            "Cash Flow From Continuing Investing Activities": {"type": ["number", "null"], "default": null},
                            "Net Other Investing Changes": {"type": ["number", "null"], "default": null},
                            "Net Business Purchase And Sale": {"type": ["number", "null"], "default": null},
                            "Purchase Of Business": {"type": ["number", "null"], "default": null},
                            "Net PPE Purchase And Sale": {"type": ["number", "null"], "default": null},
                            "Purchase Of PPE": {"type": ["number", "null"], "default": null},
                            "Operating Cash Flow": {"type": ["number", "null"], "default": null},
                            "Cash Flow From Continuing Operating Activities": {"type": ["number", "null"], "default": null},
                            "Taxes Refund Paid": {"type": ["number", "null"], "default": null},
                            "Interest Paid Cfo": {"type": ["number", "null"], "default": null},
                            "Dividend Received Cfo": {"type": ["number", "null"], "default": null},
                            "Change In Working Capital": {"type": ["number", "null"], "default": null},
                            "Other Non Cash Items": {"type": ["number", "null"], "default": null},
                            "Asset Impairment Charge": {"type": ["number", "null"], "default": null},
                            "Deferred Tax": {"type": ["number", "null"], "default": null},
                            "Deferred Income Tax": {"type": ["number", "null"], "default": null},
                            "Depreciation Amortization Depletion": {"type": ["number", "null"], "default": null},
                            "Depreciation And Amortization": {"type": ["number", "null"], "default": null},
                            "Operating Gains Losses": {"type": ["number", "null"], "default": null},
                            "Earnings Losses From Equity Investments": {"type": ["number", "null"], "default": null},
                            "Gain Loss On Investment Securities": {"type": ["number", "null"], "default": null},
                            "Net Foreign Currency Exchange Gain Loss": {"type": ["number", "null"], "default": null},
                            "Net Income From Continuing Operations": {"type": ["number", "null"], "default": null}
                        }
                    },
            "cashflow_date": {"type": ["string", "null"], "default": null},
            "balance_sheet": {"type": "object",
                              "properties": {
                                    "Ordinary Shares Number": {"type": ["number", "null"], "default": null},
                                    "Share Issued": {"type": ["number", "null"], "default": null},
                                    "Net Debt": {"type": ["number", "null"], "default": null},
                                    "Total Debt": {"type": ["number", "null"], "default": null},
                                    "Tangible Book Value": {"type": ["number", "null"], "default": null},
                                    "Invested Capital": {"type": ["number", "null"], "default": null},
                                    "Working Capital": {"type": ["number", "null"], "default": null},
                                    "Net Tangible Assets": {"type": ["number", "null"], "default": null},
                                    "Capital Lease Obligations": {"type": ["number", "null"], "default": null},
                                    "Common Stock Equity": {"type": ["number", "null"], "default": null},
                                    "Preferred Stock Equity": {"type": ["number", "null"], "default": null},
                                    "Total Capitalization": {"type": ["number", "null"], "default": null},
                                    "Total Equity Gross Minority Interest": {"type": ["number", "null"], "default": null},
                                    "Minority Interest": {"type": ["number", "null"], "default": null},
                                    "Stockholders Equity": {"type": ["number", "null"], "default": null},
                                    "Gains Losses Not Affecting Retained Earnings": {"type": ["number", "null"], "default": null},
                                    "Other Equity Adjustments": {"type": ["number", "null"], "default": null},
                                    "Foreign Currency Translation Adjustments": {"type": ["number", "null"], "default": null},
                                    "Minimum Pension Liabilities": {"type": ["number", "null"], "default": null},
                                    "Retained Earnings": {"type": ["number", "null"], "default": null},
                                    "Capital Stock": {"type": ["number", "null"], "default": null},
                                    "Common Stock": {"type": ["number", "null"], "default": null},
                                    "Preferred Stock": {"type": ["number", "null"], "default": null},
                                    "Total Liabilities Net Minority Interest": {"type": ["number", "null"], "default": null},
                                    "Total Non Current Liabilities Net Minority Interest": {"type": ["number", "null"], "default": null},
                                    "Other Non Current Liabilities": {"type": ["number", "null"], "default": null},
                                    "Derivative Product Liabilities": {"type": ["number", "null"], "default": null},
                                    "Non Current Deferred Liabilities": {"type": ["number", "null"], "default": null},
                                    "Non Current Deferred Revenue": {"type": ["number", "null"], "default": null},
                                    "Non Current Deferred Taxes Liabilities": {"type": ["number", "null"], "default": null},
                                    "Long Term Debt And Capital Lease Obligation": {"type": ["number", "null"], "default": null},
                                    "Long Term Capital Lease Obligation": {"type": ["number", "null"], "default": null},
                                    "Long Term Debt": {"type": ["number", "null"], "default": null},
                                    "Long Term Provisions": {"type": ["number", "null"], "default": null},
                                    "Current Liabilities": {"type": ["number", "null"], "default": null},
                                    "Other Current Liabilities": {"type": ["number", "null"], "default": null},
                                    "Current Deferred Liabilities": {"type": ["number", "null"], "default": null},
                                    "Current Deferred Revenue": {"type": ["number", "null"], "default": null},
                                    "Current Debt And Capital Lease Obligation": {"type": ["number", "null"], "default": null},
                                    "Current Debt": {"type": ["number", "null"], "default": null},
                                    "Other Current Borrowings": {"type": ["number", "null"], "default": null},
                                    "Current Provisions": {"type": ["number", "null"], "default": null},
                                    "Payables And Accrued Expenses": {"type": ["number", "null"], "default": null},
                                    "Current Accrued Expenses": {"type": ["number", "null"], "default": null},
                                    "Interest Payable": {"type": ["number", "null"], "default": null},
                                    "Payables": {"type": ["number", "null"], "default": null},
                                    "Dividends Payable": {"type": ["number", "null"], "default": null},
                                    "Total Tax Payable": {"type": ["number", "null"], "default": null},
                                    "Accounts Payable": {"type": ["number", "null"], "default": null},
                                    "Total Assets": {"type": ["number", "null"], "default": null},
                                    "Total Non Current Assets": {"type": ["number", "null"], "default": null},
                                    "Other Non Current Assets": {"type": ["number", "null"], "default": null},
                                    "Non Current Deferred Assets": {"type": ["number", "null"], "default": null},
                                    "Non Current Deferred Taxes Assets": {"type": ["number", "null"], "default": null},
                                    "Non Current Accounts Receivable": {"type": ["number", "null"], "default": null},
                                    "Financial Assets": {"type": ["number", "null"], "default": null},
                                    "Investments And Advances": {"type": ["number", "null"], "default": null},
                                    "Long Term Equity Investment": {"type": ["number", "null"], "default": null},
                                    "Goodwill And Other Intangible Assets": {"type": ["number", "null"], "default": null},
                                    "Other Intangible Assets": {"type": ["number", "null"], "default": null},
                                    "Goodwill": {"type": ["number", "null"], "default": null},
                                    "Net PPE": {"type": ["number", "null"], "default": null},
                                    "Accumulated Depreciation": {"type": ["number", "null"], "default": null},
                                    "Gross PPE": {"type": ["number", "null"], "default": null},
                                    "Construction In Progress": {"type": ["number", "null"], "default": null},
                                    "Other Properties": {"type": ["number", "null"], "default": null},
                                    "Machinery Furniture Equipment": {"type": ["number", "null"], "default": null},
                                    "Buildings And Improvements": {"type": ["number", "null"], "default": null},
                                    "Land And Improvements": {"type": ["number", "null"], "default": null},
                                    "Properties": {"type": ["number", "null"], "default": null},
                                    "Current Assets": {"type": ["number", "null"], "default": null},
                                    "Hedging Assets Current": {"type": ["number", "null"], "default": null},
                                    "Restricted Cash": {"type": ["number", "null"], "default": null},
                                    "Prepaid Assets": {"type": ["number", "null"], "default": null},
                                    "Inventory": {"type": ["number", "null"], "default": null},
                                    "Other Inventories": {"type": ["number", "null"], "default": null},
                                    "Raw Materials": {"type": ["number", "null"], "default": null},
                                    "Receivables": {"type": ["number", "null"], "default": null},
                                    "Other Receivables": {"type": ["number", "null"], "default": null},
                                    "Taxes Receivable": {"type": ["number", "null"], "default": null},
                                    "Accounts Receivable": {"type": ["number", "null"], "default": null},
                                    "Cash Cash Equivalents And Short Term Investments": {"type": ["number", "null"], "default": null},
                                    "Cash And Cash Equivalents": {"type": ["number", "null"], "default": null}
                                }
                            },
            "balance_sheet_date": {"type": ["string", "null"], "default": null},
            "info": {"type": "object",
                     "properties": {
                        "address1": {"type": ["string", "null"], "default": null},
                        "address2": {"type": ["string", "null"], "default": null},
                        "city": {"type": ["string", "null"], "default": null},
                        "state": {"type": ["string", "null"], "default": null},
                        "zip": {"type": ["string", "null"], "default": null},
                        "country": {"type": ["string", "null"], "default": null},
                        "phone": {"type": ["string", "null"], "default": null},
                        "website": {"type": ["string", "null"], "default": null},
                        "industry": {"type": ["string", "null"], "default": null},
                        "industryDisp": {"type": ["string", "null"], "default": null},
                        "sector": {"type": ["string", "null"], "default": null},
                        "sectorDisp": {"type": ["string", "null"], "default": null},
                        "longBusinessSummary": {"type": ["string", "null"], "default": null},
                        "fullTimeEmployees": {"type": ["number", "null"], "default": null},
                        "companyOfficers": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "maxAge": {"type": ["number", "null"], "default": null},
                                    "name": {"type": ["string", "null"], "default": null},
                                    "age": {"type": ["number", "null"], "default": null},
                                    "title": {"type": ["string", "null"], "default": null},
                                    "yearBorn": {"type": ["number", "null"], "default": null},
                                    "fiscalYear": {"type": ["number", "null"], "default": null},
                                    "totalPay": {"type": ["number", "null"], "default": null},
                                    "exercisedValue": {"type": ["number", "null"], "default": null},
                                    "unexercisedValue": {"type": ["number", "null"], "default": null}
                                }
                            }
                        },
                        "auditRisk": {"type": ["number", "null"], "default": null},
                        "boardRisk": {"type": ["number", "null"], "default": null},
                        "compensationRisk": {"type": ["number", "null"], "default": null},
                        "shareHolderRightsRisk": {"type": ["number", "null"], "default": null},
                        "overallRisk": {"type": ["number", "null"], "default": null},
                        "governanceEpochDate": {"type": ["number", "null"], "default": null},
                        "compensationAsOfEpochDate": {"type": ["number", "null"], "default": null},
                        "maxAge": {"type": ["number", "null"], "default": null},
                        "priceHint": {"type": ["number", "null"], "default": null},
                        "previousClose": {"type": ["number", "null"], "default": null},
                        "open": {"type": ["number", "null"], "default": null},
                        "dayLow": {"type": ["number", "null"], "default": null},
                        "dayHigh": {"type": ["number", "null"], "default": null},
                        "regularMarketPreviousClose": {"type": ["number", "null"], "default": null},
                        "regularMarketOpen": {"type": ["number", "null"], "default": null},
                        "regularMarketDayLow": {"type": ["number", "null"], "default": null},
                        "regularMarketDayHigh": {"type": ["number", "null"], "default": null},
                        "dividendRate": {"type": ["number", "null"], "default": null},
                        "dividendYield": {"type": ["number", "null"], "default": null},
                        "exDividendDate": {"type": ["number", "null"], "default": null},
                        "payoutRatio": {"type": ["number", "null"], "default": null},
                        "fiveYearAvgDividendYield": {"type": ["number", "null"], "default": null},
                        "beta": {"type": ["number", "null"], "default": null},
                        "trailingPE": {"type": ["number", "null"], "default": null},
                        "forwardPE": {"type": ["number", "null"], "default": null},
                        "volume": {"type": ["number", "null"], "default": null},
                        "regularMarketVolume": {"type": ["number", "null"], "default": null},
                        "averageVolume": {"type": ["number", "null"], "default": null},
                        "averageVolume10days": {"type": ["number", "null"], "default": null},
                        "averageDailyVolume10Day": {"type": ["number", "null"], "default": null},
                        "bid": {"type": ["number", "null"], "default": null},
                        "ask": {"type": ["number", "null"], "default": null},
                        "bidSize": {"type": ["number", "null"], "default": null},
                        "askSize": {"type": ["number", "null"], "default": null},
                        "marketCap": {"type": ["number", "null"], "default": null},
                        "fiftyTwoWeekLow": {"type": ["number", "null"], "default": null},
                        "fiftyTwoWeekHigh": {"type": ["number", "null"], "default": null},
                        "priceToSalesTrailing12Months": {"type": ["number", "null"], "default": null},
                        "fiftyDayAverage": {"type": ["number", "null"], "default": null},
                        "twoHundredDayAverage": {"type": ["number", "null"], "default": null},
                        "trailingAnnualDividendRate": {"type": ["number", "null"], "default": null},
                        "trailingAnnualDividendYield": {"type": ["number", "null"], "default": null},
                        "currency": {"type": ["string", "null"], "default": null},
                        "enterpriseValue": {"type": ["number", "null"], "default": null},
                        "profitMargins": {"type": ["number", "null"], "default": null},
                        "floatShares": {"type": ["number", "null"], "default": null},
                        "sharesOutstanding": {"type": ["number", "null"], "default": null},
                        "sharesShort": {"type": ["number", "null"], "default": null},
                        "sharesShortPriorMonth": {"type": ["number", "null"], "default": null},
                        "sharesShortPreviousMonthDate": {"type": ["number", "null"], "default": null},
                        "dateShortInterest": {"type": ["number", "null"], "default": null},
                        "sharesPercentSharesOut": {"type": ["number", "null"], "default": null},
                        "heldPercentInsiders": {"type": ["number", "null"], "default": null},
                        "heldPercentInstitutions": {"type": ["number", "null"], "default": null},
                        "shortRatio": {"type": ["number", "null"], "default": null},
                        "impliedSharesOutstanding": {"type": ["number", "null"], "default": null},
                        "bookValue": {"type": ["number", "null"], "default": null},
                        "priceToBook": {"type": ["number", "null"], "default": null},
                        "lastFiscalYearEnd": {"type": ["number", "null"], "default": null},
                        "nextFiscalYearEnd": {"type": ["number", "null"], "default": null},
                        "mostRecentQuarter": {"type": ["number", "null"], "default": null},
                        "earningsQuarterlyGrowth": {"type": ["number", "null"], "default": null},
                        "netIncomeToCommon": {"type": ["number", "null"], "default": null},
                        "trailingEps": {"type": ["number", "null"], "default": null},
                        "forwardEps": {"type": ["number", "null"], "default": null},
                        "pegRatio": {"type": ["number", "null"], "default": null},
                        "enterpriseToRevenue": {"type": ["number", "null"], "default": null},
                        "enterpriseToEbitda": {"type": ["number", "null"], "default": null},
                        "annualChange": {"type": ["number", "null"], "default": null},
                        "SandP52WeekChange": {"type": ["number", "null"], "default": null},
                        "lastDividendValue": {"type": ["number", "null"], "default": null},
                        "lastDividendDate": {"type": ["number", "null"], "default": null},
                        "exchange": {"type": ["string", "null"], "default": null},
                        "quoteType": {"type": ["string", "null"], "default": null},
                        "symbol": {"type": ["string", "null"], "default": null},
                        "underlyingSymbol": {"type": ["string", "null"], "default": null},
                        "shortName": {"type": ["string", "null"], "default": null},
                        "longName": {"type": ["string", "null"], "default": null},
                        "firstTradeDateEpochUtc": {"type": ["number", "null"], "default": null},
                        "timeZoneFullName": {"type": ["string", "null"], "default": null},
                        "timeZoneShortName": {"type": ["string", "null"], "default": null},
                        "uuid": {"type": ["string", "null"], "default": null},
                        "messageBoardId": {"type": ["string", "null"], "default": null},
                        "gmtOffSetMilliseconds": {"type": ["number", "null"], "default": null},
                        "currentPrice": {"type": ["number", "null"], "default": null},
                        "targetHighPrice": {"type": ["number", "null"], "default": null},
                        "targetLowPrice": {"type": ["number", "null"], "default": null},
                        "targetMeanPrice": {"type": ["number", "null"], "default": null},
                        "targetMedianPrice": {"type": ["number", "null"], "default": null},
                        "recommendationMean": {"type": ["number", "null"], "default": null},
                        "recommendationKey": {"type": ["string", "null"], "default": null},
                        "numberOfAnalystOpinions": {"type": ["number", "null"], "default": null},
                        "totalCash": {"type": ["number", "null"], "default": null},
                        "totalCashPerShare": {"type": ["number", "null"], "default": null},
                        "ebitda": {"type": ["number", "null"], "default": null},
                        "totalDebt": {"type": ["number", "null"], "default": null},
                        "quickRatio": {"type": ["number", "null"], "default": null},
                        "currentRatio": {"type": ["number", "null"], "default": null},
                        "totalRevenue": {"type": ["number", "null"], "default": null},
                        "debtToEquity": {"type": ["number", "null"], "default": null},
                        "revenuePerShare": {"type": ["number", "null"], "default": null},
                        "returnOnAssets": {"type": ["number", "null"], "default": null},
                        "returnullquity": {"type": ["number", "null"], "default": null},
                        "grossProfits": {"type": ["number", "null"], "default": null},
                        "freeCashflow": {"type": ["number", "null"], "default": null},
                        "operatingCashflow": {"type": ["number", "null"], "default": null},
                        "earningsGrowth": {"type": ["number", "null"], "default": null},
                        "revenueGrowth": {"type": ["number", "null"], "default": null},
                        "grossMargins": {"type": ["number", "null"], "default": null},
                        "ebitdaMargins": {"type": ["number", "null"], "default": null},
                        "operatingMargins": {"type": ["number", "null"], "default": null},
                        "financialCurrency": {"type": ["string", "null"], "default": null},
                        "trailingPegRatio": {"type": ["number", "null"], "default": null},
                        "isin": {"type": ["string", "null"], "default": null},
                    }
                },
            "institutions": {"type": "array",
                              "items": {
                                "type": "object",
                                "properties": {
                                    "Holder": {"type": ["string", "null"], "default": null},
                                    "Shares": {"type": ["number", "null"], "default": null},
                                    "Date Reported": {"type": ["string", "null"], "default": null},
                                    "Out_percent": {"type": ["number", "null"], "default": null},
                                    "Value": {"type": ["number", "null"], "default": null}
                                }
                              }
                            },
            "event_fingerprint": {"type": "string"},
            "event_timestamp": {"type": "string"}
        }
    }
            }
          }  

  
        }
  
      },
  );
  
  

export const schema = new GraphQLSchema({
    query: RootQuery,
});

export default schema;